
project_id = "juwbamkqkawyibcvllvo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[storage]
enabled = true

[realtime]
enabled = true

[analytics]
enabled = false
port = 54327
vector_port = 54328
gcp_project_id = ""
gcp_project_number = ""
gcp_jwt_path = "supabase/gcloud.json"

[experimental]
events = false
publications = false
subscriptions = false
trace = false

[edge_functions]
enabled = true

[edge_functions.blog-post-api]
verify_jwt = false

[edge_functions.blog-webhook]
verify_jwt = false

[edge_functions.check-newsletter-automation]
verify_jwt = false

[edge_functions.contact-form]
verify_jwt = false

[edge_functions.manage-users]
verify_jwt = false

[edge_functions.send-newsletter]
verify_jwt = false

[edge_functions.send-notification]
verify_jwt = false

[edge_functions.toggle-newsletter-automation]
verify_jwt = false

[edge_functions.translate]
verify_jwt = false

[edge_functions.translate-blog]
verify_jwt = false

[edge_functions.update-db-schema]
verify_jwt = false
