
project_id = "juwbamkqkawyibcvllvo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public", "auth"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
smtp_admin_email = "admin@example.com"

[realtime]
enabled = true

[storage]
enabled = true

[edge_functions]
enabled = true
port = 9000

[edge_functions.translate]
verify_jwt = true

[edge_functions.translate-blog]
verify_jwt = true

[edge_functions.manage-users]
verify_jwt = true
