import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

interface LanguageContextProps {
  language: string;
  setLanguage: (language: string) => void;
  t: (key: string, options?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

interface LanguageProviderProps {
  children: React.ReactNode;
}

const translations = {
  en: {
    // Navigation translations
    nav: {
      home: 'Home',
      solutions: 'Solutions',
      blog: 'Blog',
      contact: 'Contact',
      logout: 'Logout'
    },
    login: {
      welcome: 'Welcome to',
      clientWelcomeDesc: 'Client Portal - Access your automations',
      email: 'Email',
      password: 'Password',
      rememberPassword: 'Remember password',
      signIn: 'Sign In',
      loggingIn: 'Logging In...',
      loginError: 'Invalid credentials'
    },
    clientPortal: {
      title: 'Client Portal',
      subtitle: 'Manage your automations and support tickets',
      myAutomations: 'My Automations',
      marketplace: 'Marketplace',
      support: 'Support',
      myAutomationsTitle: 'Active Automations',
      myAutomationsDesc: 'Here\'s an overview of your active automations.',
      ready: 'Ready',
      total: 'Total',
      purchaseDate: 'Purchase Date',
      nextBilling: 'Next Billing',
      monthlyPrice: 'Monthly Price',
      status: 'Status',
      active: 'Active',
      cancel: 'Cancel Subscription',
      cancelSuccess: 'Subscription canceled successfully.',
      cancelError: 'Failed to cancel subscription.',
      setupPending: 'Setup Pending',
      setupInProgress: 'Setup In Progress',
      readyToUse: 'Ready to Use',
      webhook: 'Webhook',
      customPrompt: 'Custom Prompt',
      form: 'Form',
      table: 'Table',
      noActiveAutomations: 'No Active Automations',
      noActiveAutomationsDesc: 'Explore the marketplace to find the perfect automation for your needs.',
      browseMarketplace: 'Browse Marketplace',
      settingUp: 'Setting Up',
      manage: 'Manage',
      viewDetails: 'View Details',
      configure: 'Configure',
      getSupport: 'Get Support',
      description: 'Description',
      features: 'Features',
      instructions: 'Instructions',
      setupInstructions: 'Setup Instructions',
      usageInstructions: 'Usage Instructions',
      troubleshooting: 'Troubleshooting',
      integrationSettings: 'Integration Settings',
      webhookUrl: 'Webhook URL',
      customPrompts: 'Custom Prompts',
      formIntegration: 'Form Integration',
      tableData: 'Table Data',
      analytics: 'Analytics',
      logs: 'Logs',
      configuration: 'Configuration'
    },
    // Marketplace translations
    marketplace: {
      noAutomations: 'No Automations Available',
      noAutomationsDesc: 'There are currently no automations available in the marketplace.',
      setup: 'Setup',
      monthly: 'Monthly',
      features: 'Features',
      customPrompts: 'Custom prompts',
      webhooks: 'Webhooks',
      forms: 'Forms',
      tables: 'Tables',
      purchase: 'Purchase',
      viewDetails: 'View Details',
      alreadyOwned: 'You already own this automation',
      loginToPurchase: 'Please login to purchase automations',
      purchaseSuccess: 'Automation purchased successfully! Our team will set it up for you soon.',
      purchaseError: 'Failed to purchase automation',
      loading: 'Loading automations...',
      price: 'Price',
      oneTimeSetup: 'One-time setup',
      description: 'Description',
      included: 'Included features'
    },

    // Support tickets translations
    support: {
      tickets: 'Support Tickets',
      createNewTicket: 'Create New Ticket',
      noTickets: "You haven't created any support tickets yet.",
      createFirstTicket: 'Create Your First Ticket',
      selectAutomation: 'Select Automation',
      selectAutomationPlaceholder: 'Select an automation',
      title: 'Title',
      titlePlaceholder: 'Brief description of your issue',
      description: 'Description',
      descriptionPlaceholder: 'Please provide details about your issue',
      cancel: 'Cancel',
      submit: 'Submit Ticket',
      submitting: 'Submitting...',
      createSuccess: 'Support ticket created successfully',
      createError: 'Failed to create support ticket',
      loadError: 'Failed to load your support tickets',
      noActiveAutomations: 'No Active Automations',
      noActiveAutomationsDesc: 'You need an active automation to create a support ticket.',
      browseMarketplace: 'Browse Marketplace',
      backToSupport: 'Back to Support',
      ticketNotFound: "Ticket not found or you don't have permission to view it.",
      backToPortal: 'Back to Client Portal',
      ticketIdRequired: 'Ticket ID is required.',
      typeResponse: 'Type your response here...',
      sendResponse: 'Send Response',
      responseSuccess: 'Response submitted successfully',
      responseError: 'Failed to submit response',
      conversation: 'Conversation',
      noResponses: 'No responses yet',
      supportTeam: 'Support Team',
      client: 'Client',
      automationLabel: 'Automation:',
      createdLabel: 'Created:',
      status: 'Status',
      open: 'Open',
      inProgress: 'In Progress',
      resolved: 'Resolved',
      closed: 'Closed',
      priority: 'Priority',
      high: 'High',
      medium: 'Medium',
      low: 'Low'
    },

    // Advanced automation details translations
    automationDetails: {
      loadingDetails: 'Loading automation details...',
      notFound: 'Automation Not Found',
      notFoundDesc: "The automation you're looking for doesn't exist or you don't have access to it.",
      backToPortal: 'Back to Portal',
      purchaseDate: 'Purchase Date',
      nextBilling: 'Next Billing',
      status: 'Status',
      setup: 'Setup',
      setupInProgress: 'Setup in Progress',
      setupInProgressDesc: "Our team is currently configuring your automation. You'll receive a notification once it's ready to use.",
      noIntegrationsAvailable: 'No Integrations Available',
      noIntegrationsDesc: "This automation doesn't have any active integrations configured yet.",
      webhooks: 'Webhooks',
      customPrompts: 'Custom Prompts',
      forms: 'Forms',
      tables: 'Tables',
      createTicket: 'Create Ticket',
      overview: 'Overview',
      integrations: 'Integrations',
      documentation: 'Documentation',
      support: 'Support',
      settings: 'Settings',
      webhook: 'Webhook',
      customPrompt: 'Custom Prompt',
      form: 'Form',
      table: 'Table',
      active: 'Active',
      inactive: 'Inactive',
      configure: 'Configure',
      test: 'Test',
      save: 'Save',
      copy: 'Copy',
      copied: 'Copied!',
      url: 'URL',
      method: 'Method',
      headers: 'Headers',
      payload: 'Payload',
      response: 'Response',
      logs: 'Logs',
      analytics: 'Analytics',
      requests: 'Requests',
      errors: 'Errors',
      successRate: 'Success Rate',
      averageResponse: 'Average Response Time',
      lastRequest: 'Last Request',
      totalRequests: 'Total Requests',
      edit: 'Edit',
      delete: 'Delete',
      add: 'Add',
      update: 'Update',
      loading: 'Loading...',
      noData: 'No data available',
      refresh: 'Refresh'
    }
  },
  es: {
    // Navigation translations
    nav: {
      home: 'Inicio',
      solutions: 'Soluciones',
      blog: 'Blog',
      contact: 'Contacto',
      logout: 'Cerrar Sesión'
    },
    login: {
      welcome: 'Bienvenido a',
      clientWelcomeDesc: 'Portal del Cliente - Accede a tus automatizaciones',
      email: 'Correo electrónico',
      password: 'Contraseña',
      rememberPassword: 'Recordar contraseña',
      signIn: 'Iniciar Sesión',
      loggingIn: 'Iniciando Sesión...',
      loginError: 'Credenciales inválidas'
    },
    clientPortal: {
      title: 'Portal del Cliente',
      subtitle: 'Administra tus automatizaciones y tickets de soporte',
      myAutomations: 'Mis Automatizaciones',
      marketplace: 'Mercado',
      support: 'Soporte',
      myAutomationsTitle: 'Automatizaciones Activas',
      myAutomationsDesc: 'Aquí tienes una visión general de tus automatizaciones activas.',
      ready: 'Listo',
      total: 'Total',
      purchaseDate: 'Fecha de Compra',
      nextBilling: 'Próxima Facturación',
      monthlyPrice: 'Precio Mensual',
      status: 'Estado',
      active: 'Activo',
      cancel: 'Cancelar Suscripción',
      cancelSuccess: 'Suscripción cancelada exitosamente.',
      cancelError: 'Error al cancelar la suscripción.',
      setupPending: 'Configuración Pendiente',
      setupInProgress: 'Configuración en Progreso',
      readyToUse: 'Listo para Usar',
      webhook: 'Webhook',
      customPrompt: 'Prompt Personalizado',
      form: 'Formulario',
      table: 'Tabla',
      noActiveAutomations: 'Sin Automatizaciones Activas',
      noActiveAutomationsDesc: 'Explora el mercado para encontrar la automatización perfecta para tus necesidades.',
      browseMarketplace: 'Explorar Mercado',
      settingUp: 'Configurando',
      manage: 'Administrar',
      viewDetails: 'Ver Detalles',
      configure: 'Configurar',
      getSupport: 'Obtener Soporte',
      description: 'Descripción',
      features: 'Características',
      instructions: 'Instrucciones',
      setupInstructions: 'Instrucciones de Configuración',
      usageInstructions: 'Instrucciones de Uso',
      troubleshooting: 'Solución de Problemas',
      integrationSettings: 'Configuración de Integración',
      webhookUrl: 'URL del Webhook',
      customPrompts: 'Prompts Personalizados',
      formIntegration: 'Integración de Formulario',
      tableData: 'Datos de Tabla',
      analytics: 'Analíticas',
      logs: 'Registros',
      configuration: 'Configuración'
    },
    // Marketplace translations
    marketplace: {
      noAutomations: 'No Hay Automatizaciones Disponibles',
      noAutomationsDesc: 'Actualmente no hay automatizaciones disponibles en el mercado.',
      setup: 'Configuración',
      monthly: 'Mensual',
      features: 'Características',
      customPrompts: 'Prompts personalizados',
      webhooks: 'Webhooks',
      forms: 'Formularios',
      tables: 'Tablas',
      purchase: 'Comprar',
      viewDetails: 'Ver Detalles',
      alreadyOwned: 'Ya posees esta automatización',
      loginToPurchase: 'Por favor inicia sesión para comprar automatizaciones',
      purchaseSuccess: '¡Automatización comprada exitosamente! Nuestro equipo la configurará pronto.',
      purchaseError: 'Error al comprar la automatización',
      loading: 'Cargando automatizaciones...',
      price: 'Precio',
      oneTimeSetup: 'Configuración única',
      description: 'Descripción',
      included: 'Características incluidas'
    },

    // Support tickets translations
    support: {
      tickets: 'Tickets de Soporte',
      createNewTicket: 'Crear Nuevo Ticket',
      noTickets: 'Aún no has creado ningún ticket de soporte.',
      createFirstTicket: 'Crear Tu Primer Ticket',
      selectAutomation: 'Seleccionar Automatización',
      selectAutomationPlaceholder: 'Selecciona una automatización',
      title: 'Título',
      titlePlaceholder: 'Breve descripción de tu problema',
      description: 'Descripción',
      descriptionPlaceholder: 'Por favor proporciona detalles sobre tu problema',
      cancel: 'Cancelar',
      submit: 'Enviar Ticket',
      submitting: 'Enviando...',
      createSuccess: 'Ticket de soporte creado exitosamente',
      createError: 'Error al crear el ticket de soporte',
      loadError: 'Error al cargar tus tickets de soporte',
      noActiveAutomations: 'Sin Automatizaciones Activas',
      noActiveAutomationsDesc: 'Necesitas una automatización activa para crear un ticket de soporte.',
      browseMarketplace: 'Explorar Mercado',
      backToSupport: 'Volver al Soporte',
      ticketNotFound: 'Ticket no encontrado o no tienes permisos para verlo.',
      backToPortal: 'Volver al Portal del Cliente',
      ticketIdRequired: 'Se requiere ID del ticket.',
      typeResponse: 'Escribe tu respuesta aquí...',
      sendResponse: 'Enviar Respuesta',
      responseSuccess: 'Respuesta enviada exitosamente',
      responseError: 'Error al enviar la respuesta',
      conversation: 'Conversación',
      noResponses: 'Aún no hay respuestas',
      supportTeam: 'Equipo de Soporte',
      client: 'Cliente',
      automationLabel: 'Automatización:',
      createdLabel: 'Creado:',
      status: 'Estado',
      open: 'Abierto',
      inProgress: 'En Progreso',
      resolved: 'Resuelto',
      closed: 'Cerrado',
      priority: 'Prioridad',
      high: 'Alta',
      medium: 'Media',
      low: 'Baja'
    },

    // Advanced automation details translations
    automationDetails: {
      loadingDetails: 'Cargando detalles de la automatización...',
      notFound: 'Automatización No Encontrada',
      notFoundDesc: 'La automatización que buscas no existe o no tienes acceso a ella.',
      backToPortal: 'Volver al Portal',
      purchaseDate: 'Fecha de Compra',
      nextBilling: 'Próxima Facturación',
      status: 'Estado',
      setup: 'Configuración',
      setupInProgress: 'Configuración en Progreso',
      setupInProgressDesc: 'Nuestro equipo está configurando tu automatización. Recibirás una notificación cuando esté lista para usar.',
      noIntegrationsAvailable: 'No Hay Integraciones Disponibles',
      noIntegrationsDesc: 'Esta automatización aún no tiene integraciones activas configuradas.',
      webhooks: 'Webhooks',
      customPrompts: 'Prompts Personalizados',
      forms: 'Formularios',
      tables: 'Tablas',
      createTicket: 'Crear Ticket',
      overview: 'Resumen',
      integrations: 'Integraciones',
      documentation: 'Documentación',
      support: 'Soporte',
      settings: 'Configuración',
      webhook: 'Webhook',
      customPrompt: 'Prompt Personalizado',
      form: 'Formulario',
      table: 'Tabla',
      active: 'Activo',
      inactive: 'Inactivo',
      configure: 'Configurar',
      test: 'Probar',
      save: 'Guardar',
      copy: 'Copiar',
      copied: '¡Copiado!',
      url: 'URL',
      method: 'Método',
      headers: 'Encabezados',
      payload: 'Carga',
      response: 'Respuesta',
      logs: 'Registros',
      analytics: 'Analíticas',
      requests: 'Solicitudes',
      errors: 'Errores',
      successRate: 'Tasa de Éxito',
      averageResponse: 'Tiempo de Respuesta Promedio',
      lastRequest: 'Última Solicitud',
      totalRequests: 'Total de Solicitudes',
      edit: 'Editar',
      delete: 'Eliminar',
      add: 'Agregar',
      update: 'Actualizar',
      loading: 'Cargando...',
      noData: 'No hay datos disponibles',
      refresh: 'Actualizar'
    }
  },
  fr: {
    // Navigation translations
    nav: {
      home: 'Accueil',
      solutions: 'Solutions',
      blog: 'Blog',
      contact: 'Contact',
      logout: 'Se Déconnecter'
    },
    login: {
      welcome: 'Bienvenue chez',
      clientWelcomeDesc: 'Portail Client - Accédez à vos automatisations',
      email: 'Email',
      password: 'Mot de passe',
      rememberPassword: 'Se souvenir du mot de passe',
      signIn: 'Se Connecter',
      loggingIn: 'Connexion...',
      loginError: 'Identifiants invalides'
    },
    clientPortal: {
      title: 'Portail Client',
      subtitle: 'Gérez vos automatisations et tickets de support',
      myAutomations: 'Mes Automatisations',
      marketplace: 'Marché',
      support: 'Support',
      myAutomationsTitle: 'Automatisations Actives',
      myAutomationsDesc: 'Voici un aperçu de vos automatisations actives.',
      ready: 'Prêt',
      total: 'Total',
      purchaseDate: 'Date d\'Achat',
      nextBilling: 'Prochaine Facturation',
      monthlyPrice: 'Prix Mensuel',
      status: 'Statut',
      active: 'Actif',
      cancel: 'Annuler l\'Abonnement',
      cancelSuccess: 'Abonnement annulé avec succès.',
      cancelError: 'Échec de l\'annulation de l\'abonnement.',
      setupPending: 'Configuration en Attente',
      setupInProgress: 'Configuration en Cours',
      readyToUse: 'Prêt à l\'emploi',
      webhook: 'Webhook',
      customPrompt: 'Prompt Personnalisé',
      form: 'Formulaire',
      table: 'Tableau',
      noActiveAutomations: 'Aucune Automatisation Active',
      noActiveAutomationsDesc: 'Explorez le marché pour trouver l\'automatisation parfaite pour vos besoins.',
      browseMarketplace: 'Parcourir le Marché',
      settingUp: 'Configuration',
      manage: 'Gérer',
      viewDetails: 'Voir les Détails',
      configure: 'Configurer',
      getSupport: 'Obtenir de l\'Aide',
      description: 'Description',
      features: 'Fonctionnalités',
      instructions: 'Instructions',
      setupInstructions: 'Instructions de Configuration',
      usageInstructions: 'Instructions d\'Utilisation',
      troubleshooting: 'Dépannage',
      integrationSettings: 'Paramètres d\'Intégration',
      webhookUrl: 'URL du Webhook',
      customPrompts: 'Prompts Personnalisés',
      formIntegration: 'Intégration de Formulaire',
      tableData: 'Données de Tableau',
      analytics: 'Analytiques',
      logs: 'Journaux',
      configuration: 'Configuration'
    },
    // Marketplace translations
    marketplace: {
      noAutomations: 'Aucune Automatisation Disponible',
      noAutomationsDesc: 'Il n\'y a actuellement aucune automatisation disponible sur le marché.',
      setup: 'Configuration',
      monthly: 'Mensuel',
      features: 'Fonctionnalités',
      customPrompts: 'Prompts personnalisés',
      webhooks: 'Webhooks',
      forms: 'Formulaires',
      tables: 'Tableaux',
      purchase: 'Acheter',
      viewDetails: 'Voir les Détails',
      alreadyOwned: 'Vous possédez déjà cette automatisation',
      loginToPurchase: 'Veuillez vous connecter pour acheter des automatisations',
      purchaseSuccess: 'Automatisation achetée avec succès ! Notre équipe la configurera bientôt.',
      purchaseError: 'Échec de l\'achat de l\'automatisation',
      loading: 'Chargement des automatisations...',
      price: 'Prix',
      oneTimeSetup: 'Configuration unique',
      description: 'Description',
      included: 'Fonctionnalités incluses'
    },

    // Support tickets translations
    support: {
      tickets: 'Tickets de Support',
      createNewTicket: 'Créer un Nouveau Ticket',
      noTickets: 'Vous n\'avez encore créé aucun ticket de support.',
      createFirstTicket: 'Créer Votre Premier Ticket',
      selectAutomation: 'Sélectionner une Automatisation',
      selectAutomationPlaceholder: 'Sélectionner une automatisation',
      title: 'Titre',
      titlePlaceholder: 'Brève description de votre problème',
      description: 'Description',
      descriptionPlaceholder: 'Veuillez fournir des détails sur votre problème',
      cancel: 'Annuler',
      submit: 'Soumettre le Ticket',
      submitting: 'Soumission...',
      createSuccess: 'Ticket de support créé avec succès',
      createError: 'Échec de la création du ticket de support',
      loadError: 'Échec du chargement de vos tickets de support',
      noActiveAutomations: 'Aucune Automatisation Active',
      noActiveAutomationsDesc: 'Vous avez besoin d\'une automatisation active pour créer un ticket de support.',
      browseMarketplace: 'Parcourir le Marché',
      backToSupport: 'Retour au Support',
      ticketNotFound: 'Ticket introuvable ou vous n\'avez pas la permission de le voir.',
      backToPortal: 'Retour au Portail Client',
      ticketIdRequired: 'ID du ticket requis.',
      typeResponse: 'Tapez votre réponse ici...',
      sendResponse: 'Envoyer la Réponse',
      responseSuccess: 'Réponse soumise avec succès',
      responseError: 'Échec de l\'envoi de la réponse',
      conversation: 'Conversation',
      noResponses: 'Aucune réponse encore',
      supportTeam: 'Équipe de Support',
      client: 'Client',
      automationLabel: 'Automatisation:',
      createdLabel: 'Créé:',
      status: 'Statut',
      open: 'Ouvert',
      inProgress: 'En Cours',
      resolved: 'Résolu',
      closed: 'Fermé',
      priority: 'Priorité',
      high: 'Haute',
      medium: 'Moyenne',
      low: 'Basse'
    },

    // Advanced automation details translations
    automationDetails: {
      loadingDetails: 'Chargement des détails de l\'automatisation...',
      notFound: 'Automatisation Non Trouvée',
      notFoundDesc: 'L\'automatisation que vous recherchez n\'existe pas ou vous n\'y avez pas accès.',
      backToPortal: 'Retour au Portail',
      purchaseDate: 'Date d\'Achat',
      nextBilling: 'Prochaine Facturation',
      status: 'Statut',
      setup: 'Configuration',
      setupInProgress: 'Configuration en Cours',
      setupInProgressDesc: 'Notre équipe configure actuellement votre automatisation. Vous recevrez une notification quand elle sera prête.',
      noIntegrationsAvailable: 'Aucune Intégration Disponible',
      noIntegrationsDesc: 'Cette automatisation n\'a pas encore d\'intégrations actives configurées.',
      webhooks: 'Webhooks',
      customPrompts: 'Prompts Personnalisés',
      forms: 'Formulaires',
      tables: 'Tableaux',
      createTicket: 'Créer un Ticket',
      overview: 'Aperçu',
      integrations: 'Intégrations',
      documentation: 'Documentation',
      support: 'Support',
      settings: 'Paramètres',
      webhook: 'Webhook',
      customPrompt: 'Prompt Personnalisé',
      form: 'Formulaire',
      table: 'Tableau',
      active: 'Actif',
      inactive: 'Inactif',
      configure: 'Configurer',
      test: 'Tester',
      save: 'Sauvegarder',
      copy: 'Copier',
      copied: 'Copié!',
      url: 'URL',
      method: 'Méthode',
      headers: 'En-têtes',
      payload: 'Charge utile',
      response: 'Réponse',
      logs: 'Journaux',
      analytics: 'Analytiques',
      requests: 'Requêtes',
      errors: 'Erreurs',
      successRate: 'Taux de Réussite',
      averageResponse: 'Temps de Réponse Moyen',
      lastRequest: 'Dernière Requête',
      totalRequests: 'Total des Requêtes',
      edit: 'Éditer',
      delete: 'Supprimer',
      add: 'Ajouter',
      update: 'Mettre à jour',
      loading: 'Chargement...',
      noData: 'Aucune donnée disponible',
      refresh: 'Actualiser'
    }
  }
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('language') || 'en');

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = useCallback((key: string, options: Record<string, any> = {}) => {
    const keys = key.split('.');
    let value: any = translations[language as keyof typeof translations];
    for (const k of keys) {
      value = value?.[k];
    }

    if (typeof value !== 'string') {
      console.warn(`Translation not found for key: ${key} in language: ${language}`);
      return key;
    }

    let translated = value;
    for (const optionKey in options) {
      translated = translated.replace(`{{${optionKey}}}`, options[optionKey]);
    }
    return translated;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
